#include "mblas_cuda_compute_type.h"

// Used for converting mblas type to cublas type
static const std::map<mblas_compute_type_enum, cublasComputeType_t> cuda_compute_type_mappings = {
    {MBLAS_COMPUTE_16F, CUBLAS_COMPUTE_16F},
    {MBLAS_COMPUTE_16F_PEDANTIC, CUBLAS_COMPUTE_16F_PEDANTIC},
    {MBLAS_COMPUTE_32F, CUBLAS_COMPUTE_32F},
    {MBLAS_COMPUTE_32F_PEDANTIC, CUBLAS_COMPUTE_32F_PEDANTIC},
    {MBLAS_COMPUTE_32F_FAST_16F, CUBLAS_COMPUTE_32F_FAST_16F},
    {MBLAS_COMPUTE_32F_FAST_16BF, CUBLAS_COMPUTE_32F_FAST_16BF},
    {MBLAS_COMPUTE_32F_FAST_TF32, CUBLAS_COMPUTE_32F_FAST_TF32},
    {MBLAS_COMPUTE_64F, CUBLAS_COMPUTE_64F},
    {MBLAS_COMPUTE_64F_PEDANTIC, CUBLAS_COMPUTE_64F_PEDANTIC},
    {MBLAS_COMPUTE_32I, CUBLAS_COMPUTE_32I},
    {MBLAS_COMPUTE_32I_PEDANTIC, CUBLAS_COMPUTE_32I_PEDANTIC},
#if (CUDART_VERSION >= 12090)
    {MBLAS_COMPUTE_32F_EMULATED_16BFX9, CUBLAS_COMPUTE_32F_EMULATED_16BFX9},
#endif
#if defined(HAS_CUBLAS_COMPUTE_64F_EMULATED_FIXEDPOINT)
    {MBLAS_COMPUTE_64F_EMULATED_FIXEDPOINT, CUBLAS_COMPUTE_64F_EMULATED_FIXEDPOINT},
#endif
};

const std::map<mblas_compute_type_enum, cublasComputeType_t>& mblas_cuda_compute_type::get_mappings() {
    return cuda_compute_type_mappings;
}
