name: CUDA 12.9.1 Build Test

on:
  #push:
  #  branches:
  #    - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.9.1-devel-ubuntu24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake build-essential git
      
      - name: Configure CMake
        run: |
          cmake -S src -B build \
            -DWITH_CUDA=true \
            -DWITH_ROCM=false
      
      - name: Build
        run: cmake --build build
      
      - name: Build Summary
        if: always()
        run: |
          echo "CUDA 12.9.1 build complete: ${{ job.status }}"

